{% set version = "0.22.0" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-randomizr
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/randomizr_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/randomizr/randomizr_{{ version }}.tar.gz
  sha256: 1c42d45e97aae63c4a80ae78f6c095d6d8195e18a53db0d76a17acd9070435bf

build:
  merge_build_host: true  # [win]
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}              # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
  host:
    - r-base
  run:
    - r-base
    - {{ native }}gcc-libs         # [win]

test:
  commands:
    - $R -e "library('randomizr')"           # [not win]
    - "\"%R%\" -e \"library('randomizr')\""  # [win]

about:
  home: https://declaredesign.org/r/randomizr/, https://github.com/DeclareDesign/randomizr
  license: MIT
  summary: Generates random assignments for common experimental designs and  random samples for common sampling designs.
  license_family: MIT
  license_file: {{ environ["PREFIX"] }}/lib/R/share/licenses/MIT

extra:
  recipe-maintainers:
    - conda-forge/r
    - philip-khor

# Package: randomizr
# Title: Easy-to-Use Tools for Common Forms of Random Assignment and Sampling
# Version: 0.18.0
# Authors@R: c(person("Alexander", "Coppock", email = "acoppock@gmail.com", role = c("aut", "cre")), person("Jasper", "Cooper", email = "jaspercooper@gmail.com", role = c("ctb")), person("Neal", "Fultz", email = "nfultz@gmail.com", role = c("ctb"), comment = "C version of restricted partitions"))
# Description: Generates random assignments for common experimental designs and  random samples for common sampling designs.
# URL: https://declaredesign.org/r/randomizr/, https://github.com/DeclareDesign/randomizr
# BugReports: https://github.com/DeclareDesign/randomizr/issues
# Depends: R (>= 3.4.0)
# License: MIT + file LICENSE
# LazyData: true
# Encoding: UTF-8
# Suggests: knitr, dplyr, blockTools, testthat, rmarkdown, ri
# VignetteBuilder: knitr
# RoxygenNote: 6.1.1
# NeedsCompilation: yes
# Packaged: 2019-04-23 18:39:28 UTC; gdblair
# Author: Alexander Coppock [aut, cre], Jasper Cooper [ctb], Neal Fultz [ctb] (C version of restricted partitions)
# Maintainer: Alexander Coppock <acoppock@gmail.com>
# Repository: CRAN
# Date/Publication: 2019-04-23 19:30:03 UTC
