appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
provider:
  win: azure
travis:
  secure:
    BINSTAR_TOKEN: pWLQNl5GIoaUKboEV/H4n137ivcMNl2mIlBOKztgXzM5yToPIVL13cJg1xSJh5k9/HT5fxS53PgSumPgcL3126jRcVGs5MH2GyUyL1rBh5m35z9c9otN/8T7XQd0APfYlnblBcdjqhiKQdnfbsF778lZ507kZJ5RFQm94WgkT8+0pmfeAmgp4Cytfsc0tJTzq5p1WmS6gvzQti+peK8hsg0PGNx6FUmakZnfW6PGxYVLgRQp2vpqXxNL9CQUXB6VlB/7CJVXefXuhhdxnnhVJYIeMkQa2gAXuddpmMo4G4F7lrQ/RcODGxHCWK2O63UGscsiPVx/CAM3riA0dmrlRP+EFqI4HX/53LVMAt08sB4zQ7sfBOt952ozAovwW+ReSU0C6OzpkypLIb2gZUl0EIBYc4cOBJV6d1kQmIOrEMQpIz8nuyrgokyrACgkUbrLl5Ly65WqbsZE0i9ZSPQGmLGGbust7d5BYLQ7FOeyxVZh0n4edWPFPgSwxlFpmsKAG035ABOUSg2sO93jR5vHXoP3mfIaOM0vETeYPgF79Ap1Mhmi070A+TsjhZ3v9jDBRhzmQQQEcYFpNg3ktUW7CyS4rVCx/P9PzGP4IWa+ukPCeQRVDdDxKuPUZoCxF20qJNRt7RIjPRs5sLmQE/36jz3ajCMQncTX8HeiOY9H7as=
conda_forge_output_validation: true
